### PR TITLE
Make stickiness work in overflown elements

### PR DESCRIPTION
**Pull request by Swizec**
This pull request makes it possible to use stickyfill from within overflown blocks. I tried to keep my changes as minimal as possible.

### CODE REVIEW

**Comment by wilddeer** [comment]
Hey, I'll be able to review this in a week or so, sorry for the delay!

And you can of course remind me about this PR in case I forget.

Thanks!

**Comment by wilddeer** [comment]
I tried your test page. I had to set `.overflown` height to 700px, cause 90% doesn't work.

Your implementation seem to only work when the scroll of the page is at the very top. Otherwise there're all sorts of glithes:

glitch example

glitch example

Can't merge this in it's current state.

**Comment by Swizec** [comment]
Ooh, you're right. I didn't notice that.

Will fix in the next couple of days.

**Comment by bakura10** [comment]
Hi,

Any news for this feature ? :)

**Comment by Swizec** [comment]
Hey,

I know the problem - when calculating offsets, have to account for real
offset of area from edge accounting for scroll.
Actually fixed that in the copy I was using on the project where I needed
this (https://github.com/google/ggrc-core).

Then got distracted before I submitted changes upstream. Sorry about that.

Will fix this ASAP!

Cheers

**Comment by Eternity-Yarr** [comment]
Yeeah, this ASAP, man :)

**Comment by PhilippSoehnlein** [comment]
@Swizec Any chance on updating the PR soon? I need the exact same feature you proposed, so if you can update to your last state it would be great (if there's stuff missing, I may have the time to fill in).

**Comment by Eternity-Yarr** [comment]
>_<

**Pull request closed without merging**
